// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqc49fkKF7wcRCtlFGv1lT4ZJD7sqsNGI',
    appId: '1:684076780638:web:3a337aabfa87c97661b8cf',
    messagingSenderId: '684076780638',
    projectId: 'quantum-todo-app',
    authDomain: 'quantum-todo-app.firebaseapp.com',
    storageBucket: 'quantum-todo-app.firebasestorage.app',
    measurementId: 'G-X7HY4CW2YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMTqu_KrG-ezRJGRVzU-esr2jK5iJcL64',
    appId: '1:684076780638:android:407044a4b6c7871461b8cf',
    messagingSenderId: '684076780638',
    projectId: 'quantum-todo-app',
    storageBucket: 'quantum-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4zkJJnqVTnjO0CwltBOSAcXVOrJGByE',
    appId: '1:684076780638:ios:775d1d1ae10c64a661b8cf',
    messagingSenderId: '684076780638',
    projectId: 'quantum-todo-app',
    storageBucket: 'quantum-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.quantumTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW4zkJJnqVTnjO0CwltBOSAcXVOrJGByE',
    appId: '1:684076780638:ios:775d1d1ae10c64a661b8cf',
    messagingSenderId: '684076780638',
    projectId: 'quantum-todo-app',
    storageBucket: 'quantum-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.quantumTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqc49fkKF7wcRCtlFGv1lT4ZJD7sqsNGI',
    appId: '1:684076780638:web:a7328bcb51ad8a7a61b8cf',
    messagingSenderId: '684076780638',
    projectId: 'quantum-todo-app',
    authDomain: 'quantum-todo-app.firebaseapp.com',
    storageBucket: 'quantum-todo-app.firebasestorage.app',
    measurementId: 'G-C6SQ0FJ13Z',
  );
}
